markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: yexingming
    description: learn and to be better
    title: blog of yxm
    url: drunked-monster.github.io
author:
    name: 叶兴明
    email: 2276579898@qq.com
    QQ: 2276579898
    github: https://github.com/drunked-monster
    logo: /res/img/yexingming.jpg
